### ISSUE TITLE
Image Container 1 & 2

### ISSUE THREAD

**Issue by RonaldRusso94** [RonaldRusso94/LimeLightDevs#12]
Create
Components > ImageContainer.js

Note: Make ImageContainer reusable and pass and image and text as children into ImageContainer.js
(use flexbox and pass class flex row reverese to reverse image and text in reusable component

```
const ImageContainer = ({children, className}) => {
  return (
    <div>
      {children}
    </div>
  )
}
```

services.js 
```
 <ImageContainer className="flex flex-row-reverse"><img src=""> etc... <ImageContainer/>
```

**Comment by ShinteiMai** [comment]
Working on it

**Comment by ShinteiMai** [comment]
I have added the image container component in the img-container branch, i think we could improve this component a lot by creating some props to control the image container theme, i haven't thought a lot about this tho. but for the basic use case i just used your code and it works perfectly fine.

**Comment by RonaldRusso94** [comment]
Still needs responsiveness

**Comment by ShinteiMai** [comment]
Okay, i will add some "default classes" that you can add in the top of props classes

**Comment by ShinteiMai** [comment]
I have done pushing the new Image Container that i have been refactoring. You can see the new push at img-container branch, i took this approach from react-native-paper where you want to group some related components as a children and they would use this [<List.Section>](https://callstack.github.io/react-native-paper/list-section.html)

A mini example how you would implement the new image component would be:
```javascript
import * as Image from "./Image"

return (
<Image.Container className="mt-4">
  <Image.Component src="enter image url here" alt="im an image lol" />
  <Image.Section>
     <h1>This is the content!</h1>
     <p>you can also import another component into this section</p>
  <Image.Section/>
</Image.Container>
);
```
I attached another example how to use the component at index.js and also there are propTypes
